### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by sfc-gh-space** [DataToolsPro/SnowUDFExcel#1]
Minor typos in the README: Expermintal -> Experimental

**Comment by rmgoodm** [comment]
Thanks. Put everything through spell check ;)

**Comment by sfc-gh-space** [comment]
I still see at least one typo in there: HOLDIAYS -> HOLIDAYS

**Comment by rmgoodm** [comment]
Thank you
HOLDIAYS → should be HOLIDAYS (multiple instances).
UFDs → should be UDFs.
